linkwarden:
  domain: "linkwarden.helm.private"
  nextAuthSecret:
    existingSecret:
      name: "linkwarden-nextauth"
      key: "token"
  ignoreUnauthorizedCA: true
  #  data:
  #    filesystem:
  #      pvc:
  #        existingClaim: linkwarden-pvc

  database:
    existingSecret: "linkwarden-db"
    urlKey: "uri"

  auth:
    disableRegistration: false
    enableCredentials: true
    disableNewSSOUsers: false
    sso: []
#      - provider: "authentik"
#        customName: "authentik-custom"
#        issuer: "authentik"
#        existingSecret: "authentik-creds"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: development-issuer
  tls:
    - secretName: linkwarden-ingress-tls
      hosts:
        - "linkwarden.helm.private"

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true

